# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opun < Formula
  desc "AI code agent automation framework"
  homepage "https://github.com/rizome-dev/opun"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rizome-dev/opun/releases/download/v0.1.7/opun_Darwin_x86_64.tar.gz"
      sha256 "035467540a23a7a80daecaa7a0e86f3515970425337e116a7e860d2bb238707a"

      define_method(:install) do
        bin.install "opun"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"opun", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rizome-dev/opun/releases/download/v0.1.7/opun_Darwin_arm64.tar.gz"
      sha256 "04a983a93dfbaebf5faff7618eee895114c1ee387e1352c123ad1f7af79160d1"

      define_method(:install) do
        bin.install "opun"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"opun", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rizome-dev/opun/releases/download/v0.1.7/opun_Linux_x86_64.tar.gz"
      sha256 "c3089e5b390fd7593c16ea2e496c26bb7e25fd3506f42b7f0b586e871a447cbe"
      define_method(:install) do
        bin.install "opun"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"opun", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rizome-dev/opun/releases/download/v0.1.7/opun_Linux_arm64.tar.gz"
      sha256 "510270ea00cb563c67817b530cfa2de54de88213038881a6363675464074b08c"
      define_method(:install) do
        bin.install "opun"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"opun", "completion")
      end
    end
  end

  test do
    system "#{bin}/opun", "--version"
  end
end
